version: '3.8'

services:
  api:
    container_name: "permission-manager-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8003:8080
    environment: # Poner estas variables en un archivo .env
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: permission-manager-db
      DB_HOST: postgres_db
      DB_PORT: 5433
  db:
    container_name: permission-manager-db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment: # Poner estas variables en un archivo .env
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: permission-manager-db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "tomi.serra@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  pgdata:
    external: false