version: '3.8'

services:
  db:
    container_name: permission-manager-db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment: # Poner estas variables en un archivo .env
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: permission-manager-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false