spring:
  application:
    name: back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:permission-manager-db}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:admin}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:admin}}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}

snippet:
  manager:
    url: ${SNIPPET_MANAGER_URL:http://localhost:8000}

printscript:
  service:
    url: ${PRINTSCRIPT_SERVICE_URL:http://localhost:8004}

auth0:
  audience: ${AUTH0_AUDIENCE}

server:
  port: ${DOCKER_PORT:8003}

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
